POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How music helps in enhancing emotional context understanding",
  "author": "Devansh Mahalle",
  "url": "http://localhost:3003/api/blogs",
  "likes": 25000
}